"""Places Schema Change

Revision ID: 8c0a27c5e159
Revises: ecf888b070fd
Create Date: 2025-02-26 11:46:39.910163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c0a27c5e159'
down_revision: Union[str, None] = 'ecf888b070fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('places', sa.JSON(), nullable=True))
    op.alter_column('trips', 'best_time_to_visit',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('trips', 'place')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('place', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('trips', 'best_time_to_visit',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('trips', 'places')
    # ### end Alembic commands ###
