"""Little Schema Change

Revision ID: b92dbe36a930
Revises: fe292ee16f47
Create Date: 2025-02-26 12:36:23.728339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b92dbe36a930'
down_revision: Union[str, None] = 'fe292ee16f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'about',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'about',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
