"""Increase best_time_to_visit column size

Revision ID: ecf888b070fd
Revises: ea0a8956256e
Create Date: 2025-02-24 10:53:09.038609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf888b070fd'
down_revision: Union[str, None] = 'ea0a8956256e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
